### ISSUE TITLE
Transaction Fee Not Available For Unregistered Users

### ISSUE THREAD

**Issue by nicolo** [paypal/PayPal-Ruby-SDK#108]
Transaction fee seems to return nil for any payment made from an unregistered paypal user. I believe this is the case when the user does not log in, but they instead just make a payment with their credit card.

Typically transaction_fee returns the fee amount, but in this case it returns nil

**Comment by jaypatel512** [comment]
I tried to complete the flow where I used a sandbox credit card to complete the transaction instead of logging into the account (guest/unregistered paypal user), and on execute, I got the following data:

```json
{
    "id": "PAY-85J46188GM499434AKUIELII",
    "create_time": "2015-03-23T16:56:01Z",
    "update_time": "2015-03-23T16:57:58Z",
    "state": "approved",
    "intent": "sale",
    "payer": {
        "payment_method": "paypal",
        "payer_info": {
            "email": "jaypatel512@gmail.com",
            "first_name": "Jay",
            "last_name": "Patel",
            "payer_id": "Y3KZ4RVJDKVK6",
            "shipping_address": {
                "line1": "123 Cascada Lane,",
                "city": "Round Rock",
                "state": "TX",
                "postal_code": "78681",
                "country_code": "US",
                "recipient_name": "Jay Patel"
            }
        }
    },
    "transactions": [
        {
            "amount": {
                "total": "20.00",
                "currency": "USD",
                "details": {
                    "subtotal": "17.50",
                    "tax": "1.30",
                    "shipping": "1.20"
                }
            },
            "description": "Payment description",
            "item_list": {
                "items": [
                    {
                        "name": "Ground Coffee 40 oz",
                        "price": "7.50",
                        "currency": "USD",
                        "quantity": "1"
                    },
                    {
                        "name": "Granola bars",
                        "price": "2.00",
                        "currency": "USD",
                        "quantity": "5"
                    }
                ],
                "shipping_address": {
                    "recipient_name": "Jay Patel",
                    "line1": "123 Cascada Lane,",
                    "city": "Round Rock",
                    "state": "TX",
                    "postal_code": "78681",
                    "country_code": "US"
                }
            },
            "related_resources": [
                {
                    "sale": {
                        "id": "9RL212368W0425208",
                        "create_time": "2015-03-23T16:56:01Z",
                        "update_time": "2015-03-23T16:57:58Z",
                        "amount": {
                            "total": "20.00",
                            "currency": "USD"
                        },
                        "payment_mode": "INSTANT_TRANSFER",
                        "state": "completed",
                        "protection_eligibility": "ELIGIBLE",
                        "protection_eligibility_type": "ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE",
                        "parent_payment": "PAY-85J46188GM499434AKUIELII",
                        "transaction_fee": {
                            "value": "0.88",
                            "currency": "USD"
                        },
                        "links": [
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/sale/9RL212368W0425208",
                                "rel": "self",
                                "method": "GET"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/sale/9RL212368W0425208/refund",
                                "rel": "refund",
                                "method": "POST"
                            },
                            {
                                "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-85J46188GM499434AKUIELII",
                                "rel": "parent_payment",
                                "method": "GET"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "links": [
        {
            "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAY-85J46188GM499434AKUIELII",
            "rel": "self",
            "method": "GET"
        }
    ]
}
```

Can you please confirm if I missed any steps here? If not, can you please provide us with the debug_id (part of header information) to retrieve internal information about the data you are trying to send.

**Comment by nicolo** [comment]
Here is an example payment id PAY-02K44502CM4294050KUI3JMI for sandbox where this problem occurs.

The json you have above appears to not be an unregistered user because you can see the response has full payer information. I could be wrong.
```
 "payer": {
        "payment_method": "paypal",
        "payer_info": {
            "email": "jaypatel512@gmail.com",
            "first_name": "Jay",
            "last_name": "Patel",
            "payer_id": "Y3KZ4RVJDKVK6",
            "shipping_address": {
                "line1": "123 Cascada Lane,",
                "city": "Round Rock",
                "state": "TX",
                "postal_code": "78681",
                "country_code": "US",
                "recipient_name": "Jay Patel"
            }
        }
`````

**Comment by nicolo** [comment]
@jaypatel512 Any update on this? Did you get a chance to look at the payment id I posted?

**Comment by ppmtscory** [comment]
@nicolo I'm seeing that transaction_fee is being returned in the Execute response of a 'guest checkout' (entering card instead of logging in).  Feel free to reopen or create a new issue if you are still having trouble.

`{"id":"PAY-3MP936364X870990GKYEWTNY","intent":"sale","state":"approved","cart":"6G366552FE965313R","payer":{"payment_method":"paypal","payer_info":{"first_name":"Unregister","last_name":"Test","payer_id":"F7CEAZJSK65PN","shipping_address":{"recipient_name":"Unregister Test","id":"31224974","line1":"123 main st","city":"BEVERLY HILLS","state":"CA","postal_code":"90210","country_code":"US"},"phone":"8882211161","country_code":"US","billing_address":{"line1":"123 main st","line2":"","city":"beverly hills","state":"CA","postal_code":"90210","country_code":"US"}}},"transactions":[{"amount":{"total":"1.00","currency":"USD","details":{"subtotal":"1.00","tax":"0.00","shipping":"0.00"}},"description":"This is the payment transaction description.","item_list":{"shipping_address":{"id":"31224974","line1":"123 main st","city":"BEVERLY HILLS","state":"CA","postal_code":"90210","country_code":"US"}},"related_resources":[{"sale":{"id":"6UX11425W0907245Y","state":"completed","amount":{"total":"1.00","currency":"USD","details":{"subtotal":"1.00","tax":"0.00","shipping":"0.00"}},"coupled_group":0,"payment_mode":"INSTANT_TRANSFER","protection_eligibility":"ELIGIBLE","protection_eligibility_type":"ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE","transaction_fee":{"value":"0.33","currency":"USD"},"receipt_id":"3358979627860403","parent_payment":"PAY-3MP936364X870990GKYEWTNY","create_time":"2015-09-28T16:40:40Z","update_time":"2015-09-28T16:40:40Z","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/sale/6UX11425W0907245Y","rel":"self","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/payments/sale/6UX11425W0907245Y/refund","rel":"refund","method":"POST"},{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-3MP936364X870990GKYEWTNY","rel":"parent_payment","method":"GET"}],"soft_descriptor":"PAYPAL *CORYTESTSTE"}}],"coupled_group":0}],"create_time":"2015-09-28T16:40:41Z","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-3MP936364X870990GKYEWTNY","rel":"self","method":"GET"}]}`

**Comment by nicolo** [comment]
I'm still seeing the issue. It might be returned in the json but it's not getting to the payment object in the Ruby SDK. The payment id PAY-02K44502CM4294050KUI3JMI for the sandbox environment displays the issue still.
