### ISSUE TITLE
How to show discount amount on payapl response

### ISSUE THREAD

**Issue by DevilalDheer** [paypal/PayPal-Ruby-SDK#155]
I want to show discount amount on paypal after applying discount on cart.

Currently I am refer like this: https://github.com/paypal/PayPal-PHP-SDK/issues/55

**Comment by ppmtscory** [comment]
@DevilalDheer have you attempted to send a negative line item amount?  Are you receiving an error or can you provide any further context as to what's happening versus what you expect to happen?

**Comment by DevilalDheer** [comment]
Hi @ppmtscory,  Thanks for quick response. 
Yes, I have set discount as the negative line item amount if discount is available without any error and its working fine for me. 
But I want a separate field for the carts, discount like PayPal classic API. 
Are there any option in PayPal Rest API to show the discount as field like PayPal classic API?
Thanks

**Comment by ppmtscory** [comment]
Classic API (Express Checkout) uses negative item amounts to show discounts as well - aside from the shipping discount (shipdiscamt).  Can you clarify which field exactly you are looking for?

**Comment by DevilalDheer** [comment]
I am looking for field like discount_amount_cart.
This is single discount amount charged cart-wide.
Reference :
1.https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/cart_upload/
2. https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/

**Comment by ppmtscory** [comment]
Ah - ok, those are for the PayPal Standard buttons and not for the APIs.  With that being said, those were implemented into the Classic API by providing a negative line item value so that is what is translated to the RESTful APIs as a way to keep things somewhat consistent.  I don't foresee any additions of like variables since the functionality exists with negative values, however, if we do in the future, I will try to update you as such.

**Comment by DevilalDheer** [comment]
Ok @ppmtscory Thanks :+1:
