### ISSUE TITLE
Downloading recurring payments made via subscription

### ISSUE THREAD

**Issue by dmitrypol** [paypal/PayPal-Ruby-SDK#160]
Does anyone know how to download PayPal subscription payments via some kind of reporting API? 
I see references to web-hooks but would prefer to initiate download from my side.

**Comment by ppmtscory** [comment]
I don't know of anything specific, but you can [search for transactions](https://developer.paypal.com/docs/api/#search-for-transactions) within a specific billing agreement.  Otherwise, yes, you could utilize [Webhooks](https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/#event-type-support) and/or explore what options are available within the reporting within your account (even thought that's not API based).  You may also want to reach out to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) in case there's something that I'm not fully aware of.
