### ISSUE TITLE
Payment through credit card without purchasing the pro-account.

### ISSUE THREAD

**Issue by ErPuneetGoel** [paypal/PayPal-Ruby-SDK#164]
Hi Paypal,

I have created an application with Paypal integration. I have switched to live mode. On Live i am able to pay through Paypal account. It was mentioned somewhere that we need to activate the Paypal Pro-Account for successful integration of credit card payment as well. I just want to confirm is it possible to allow users to pay through credit/debit card without purchasing pro-account.

**Comment by ppmtscory** [comment]
If your merchant account is in the UK, then yes, you'll need to upgrade to a Pro account in order to process direct credit card payments.  However, the PayPal payment option also offers a guest checkout option on the PayPal page (after redirect) for eligible countries/regions where buyers can enter a credit/debit card instead of logging into a PayPal account.  For any further information on this topic, please reach out to our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team.
