### ISSUE TITLE
How to paypal page open with credit-card option landing type as billing

### ISSUE THREAD

**Issue by DevilalDheer** [paypal/PayPal-Ruby-SDK#165]
When I am going to Paypal page during place order, then its open the Paypal mobile login page,
But I wants to checkout billing page for non-Paypal account user. 

I have set landing-page: 'billing' but its not working on mobile view.

Please let me know if there are any other options.

Ref: https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECOnMobileDevices/
Specify that the buyer is not required to have a PayPal account:
SOLUTIONTYPE=Sole
Specify whether the buyer lands on the checkout billing page or the PayPal mobile login page to complete the payment.
LANDINGPAGE=Billing places the buyer on the billing page.

Thanks

**Comment by ppmtscory** [comment]
@DevilalDheer that page you referenced is specific to the Classic Express Checkout APIs and not this particular REST API Ruby SDK.  Can you please file a ticket with our [Merchant Tech Support](https://www.paypal-techsupport.com/app/ask) team so that they can review your code and file a bug with the appropriate team if necessary?
