### ISSUE TITLE
Capture a future payment instead of authorizing it

### ISSUE THREAD

**Issue by holgersindbaek** [paypal/PayPal-Ruby-SDK#169]
I'm authorizing future payments and then capturing those payments manually via the dashboard now.

Right now my code looks like this:

      # Create future payment hash
      future_payment_hash = {
        "intent" =>  "authorize",
        "payer" =>  { "payment_method" =>  "paypal" },
        "transactions" =>  [ {
          "amount" =>  {
            "total" =>  "#{charge_amount.to_i}.00",
            "currency" =>  "USD" },
          "description" =>  "Slang - #{listing.headline}" } ]
        }

      # Get new payment token
      begin
        token  = Tokeninfo.refresh(buyer.paypal_token)
      rescue PayPal::SDK::Core::Exceptions::ServerError => err
        # Reset status
        firebase.update("listings/#{@listing_id}", {status: "active"})

        # Return error message
        error_message(err)
        return
      end

      # Create payment
      future_payment = FuturePayment.new(future_payment_hash.merge( :token => token.access_token ))

Can I capture payments straight away using future payments? How would my code above look if I wanted to do that?!

**Comment by ppmtscory** [comment]
If you wanted to capture payments right away instead of doing an authorization and then capture, just use `sale` instead of `authorize` for the `intent`.  However, if you still want the Auth first, then you'd need to run a subsequent [capture](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/samples/authorization/capture.rb) call.
