### ISSUE TITLE
How to send money from one account to another via API?

### ISSUE THREAD

**Issue by mailcorpo** [paypal/PayPal-Ruby-SDK#173]
Hi. I need to integrate into my project payments with the PayPal. Students must pay from their PP account to the Teachers PP account.

All your examples is for payment to the account, that configured in config/paypal.yml. But how can I do payment from Student account to the Teachers ?

Thanks

**Comment by ppmtscory** [comment]
@mailcorpo third party processing is not available with the standard REST API.  If you are not going to take a piece of the payment, then you would just use the Teacher's account in the config file so that they receive the funds.  If you are looking to take a piece of the payment, then you'll need to look at [this page](https://developer.paypal.com/docs/marketplace-split-payments/) that provides you a couple different options.

**Comment by mailcorpo** [comment]
But what about Adaptive Payments? I found that I can send money to some email/phone PayPal account, redirecting to the PayPal page where user login and approve the pay

**Comment by ppmtscory** [comment]
@mailcorpo the previous page I mentioned has Adaptive Payments listed in it for you to reference.  It talks about Braintree Marketplace as well as Adaptive Payments.  AP would be useful if you are looking to take a piece of the payment.  If that's the case, then you'd need to look into Chained Payments.
