### ISSUE TITLE
not receiving webhooks

### ISSUE THREAD

**Issue by kaiomagalhaes** [paypal/PayPal-Ruby-SDK#255]
### General Information

- Mode (Sandbox/Live): sandbox
- PayPal-Debug-ID(s) (from any logs): ["b690b021186d9", "b690b021186d9"]
- Version of Ruby used: 3.1
- SDK Version:  paypal-sdk-rest (1.5.0)
### Issue Description

Payment id: `PAY-4FT15697YM252011BLATAVKY`

I'm using the paypal payment and for some reason I'm not receiving any hooks in my paypal sandbox accounts when I create the payment url or when I [execute the payment](https://github.com/paypal/PayPal-Ruby-SDK#execute-payment) 

Any ideas about why it isn't happening?

**Comment by kaiomagalhaes** [comment]
@bluk the issue I mentioned yesterday ^

**Comment by bluk** [comment]
@kaiomagalhaes I am getting webhooks in my test application for payment for events like `PAYMENT.AUTHORIZATION.CREATED` but I've opened internal issue PPPLPAYPT-14866 to see if there's something else. You may also want to open an issue with [Merchant Technical Support](https://www.paypal-techsupport.com/app/ask).

I would try to use something like https://requestb.in to capture responses just in case there's anything specific about your setup (you can use `https` instead of the `http` URL that requestb.in gives you) . Also some users in the past have created payments in one sandbox application but configured webhooks in another sandbox application.

**Comment by kaiomagalhaes** [comment]
@bluk  discovered the issue. Thanks for the requestb.in it helped me a lot. I was not registering the webhooks, this is why I wasn't receiving it. Thanks!
