### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by ankitbibiyaan** [paypal/PayPal-Ruby-SDK#310]
### General information

* SDK/Library version: paypal-rest-sdk":"1.7.1"
* Environment: Sandbox 
* `PayPal-Debug-ID` values: 13400819b3966
* Language, language version, and OS: 

### Issue description

paypal.payment.create function is returning internal server error and returning response after 31 sec

**Comment by pp-randy** [comment]
This is due to an overused credit card number in our sandbox environment.  Please see https://github.com/paypal/PayPal-REST-API-issues/issues/22, and try a new credit card number with the link found in this issue.

I would encourage seeing if our Braintree offerings support your credit card needs if you are just beginning to integrate https://www.braintreepayments.com/.
